pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build
      - check-success=commitlint
      - check-success=lint
      - check-success=test
    actions:
      merge:
        method: merge
