name: commitlint
on: pull_request

jobs:
  commitlint:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit messages
        run: |
          npm install @commitlint/{cli,config-conventional}
          npx commitlint --from=HEAD~1
