name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install --prefer-offline

      - name: Run ESLint
        run: npm run lint

      - name: Type check
        run: |
          npm run lint:tsc
          npm run lint:tsc:cypress
